[package]
name = "oif_starknet"
version = "0.1.0"
edition = "2024_07"

[dependencies]
alexandria_bytes = "0.4.0"
contracts = { path = "../../hyperlane-starknet/cairo/" }
mocks = { path = "../../hyperlane-starknet/cairo/" }
openzeppelin_token = "0.20.0"
openzeppelin_access = "0.20.0"
openzeppelin_account = "0.20.0"
openzeppelin_introspection = "0.20.0"
openzeppelin_upgrades = "0.20.0"
openzeppelin_utils = "0.20.0"
permit2 = { path = "../../permit2-starknet/target/package/permit2-0.1.0/" }
starknet = ">=2.10.1"
token = { path = "../../hyperlane-starknet/cairo/" }

[dev-dependencies]
snforge_std = "0.38.3"
assert_macros = ">=2.10.1"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
