[package]
name = "oif_ztarknet"
version = "0.0.1"
edition = "2024_07"

[dependencies]
alexandria_bytes = "0.6.0"
alexandria_encoding = "0.6.0"
openzeppelin_token = "2.0.0"
openzeppelin_access = "2.0.0"
openzeppelin_account = "2.0.0"
openzeppelin_introspection = "2.0.0"
openzeppelin_upgrades = "2.0.0"
openzeppelin_utils = "2.0.0"
permit2 = { git = "https://github.com/NovemberFork/permit2-ztarknet.git" }
contracts = { git = "https://github.com/NovemberFork/hyperlane-ztarknet.git", rev = "97e4d98449d33194af137e52ed259fd39fdaad19" }
mocks = { git = "https://github.com/NovemberFork/hyperlane-ztarknet.git", rev = "97e4d98449d33194af137e52ed259fd39fdaad19" }
token = { git = "https://github.com/NovemberFork/hyperlane-ztarknet.git", rev = "97e4d98449d33194af137e52ed259fd39fdaad19" }

starknet = "2.12.2"

[dev-dependencies]
snforge_std = "0.49.0"
assert_macros = "2.12.2"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
